### ISSUE TITLE
Get traffic for all ports: HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by llyaiyyl** [shadowsocks/shadowsocks-restful-api#3]
hi:
I use ubuntu 16.04, install shadowsocks-libev and shadowsocks-restful-api now.

when use login api and others it works. but then I use get traffic for all ports api, the server return:  (i have create a port)
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 12
ETag: W/"c-3Rk1bge0s6VuJbi+S2m2iU0UGdY"
Date: Thu, 09 Aug 2018 01:16:51 GMT
Connection: keep-alive

```

**Comment by llyaiyyl** [comment]
when i use last commit(3d69bf3), it works!

**Comment by Eggham** [comment]
good to know it was an old bug that had been fixed
