### ISSUE TITLE
https://localhost:4001/traffic/all. returned 500 error

### ISSUE THREAD

**Issue by rchen9012** [shadowsocks/shadowsocks-restful-api#4]
<img width="1371" alt="aae150ac-7f06-4551-b53f-3a16af5c8d9e" src="https://user-images.githubusercontent.com/387998/43942901-533293ae-9cac-11e8-9145-f94f748ce626.png">

**Comment by Eggham** [comment]
fix with 72fea95 and thanks

**Comment by rchen9012** [comment]
confirm working
