### ISSUE TITLE
Traffic for single port?

### ISSUE THREAD

**Issue by jibon57** [shadowsocks/shadowsocks-restful-api#5]
Thanks for you great work :). How to get traffic for single port instated of calling for all?

**Comment by Eggham** [comment]
Thanks for your question. There is no api for getting traffic of a single port. 

I cannot think of a use scenario for this api. You can always get traffic for a port from the traffic for all ports.

Would you please justify the need for such an api?

If there is a valid reason to show the necessity of such an api, I am happy to add it.

**Comment by jibon57** [comment]
@Eggham thanks for your reply. Actually I am creating a component for Joomla using this API. I want to show traffic usage for each user when they will access their panel. At present I will need to call all the ports' traffic but need only one. I know it's possible to run in a loop to get that particular port but will be better if can get for single.

**Comment by Eggham** [comment]
@jibon57 Thanks for your reply. The traffic data provided by the shadowsocks-restful-api is retrieved from shadowsocks-libev. The traffic data does not survive shadowsocks-libev restart. Hence it is recommended to write some logic at a higher level to persist the data into a database and let user request from the database.

You may try [shadowsocks-hub](https://github.com/shadowsocks/shadowsocks-hub.git) or [shadowsocks-hub-api](https://github.com/shadowsocks/shadowsocks-hub-api.git).

**Comment by jibon57** [comment]
@Eggham thanks again for response. Actually I want to use this one for Joomla & that one already has DB feature. 
> The traffic data provided by the shadowsocks-restful-api is retrieved from shadowsocks-libev

That mean I will need to create some cron job to retrieve the traffic from shadowsocks & update the DB... right?

**Comment by jibon57** [comment]
@Eggham, Another question. If I use `shadowsocks-hub-api`, what will be happen if user cross the bandwidth limit? Will they get disconnected?

**Comment by Eggham** [comment]
@jibon57 Yes. If a user's total usage across all accounts from a product is greater than the traffic specified in the product, then all the accounts will get disconnected and deleted.

**Comment by Eggham** [comment]
> That mean I will need to create some cron job to retrieve the traffic from shadowsocks & update the DB... right?

That's right. You should periodically retrieve traffic for all ports from shadowsocks-restful-api and update the database (e.g. once a few minutes). Otherwise, you may loose some traffic data.

**Comment by jibon57** [comment]
Thanks @Eggham for your suggestions. I have created one component for Joomla. You are welcome to check it out ;) from here: https://github.com/jibon57/com_shadowsocks

**Comment by Eggham** [comment]
@jibon57 Interesting! I will take some time to have a close look. Thank you!
