### ISSUE TITLE
support encrypt_method

### ISSUE THREAD

**Issue by musnow** [shadowsocks/shadowsocks-restful-api#7]
I hope support encrypt_method
Above the shadowsocks-libev is a field that can support all configurations, add it in the json content.

shadowsocks-restful-api above I tried to add fields on the new interface without any reaction, I hope to get support,
thank you

https://github.com/shadowsocks/shadowsocks-libev/issues/1984

**Comment by Eggham** [comment]
Interesting. I'll dig into it. Thanks for the information.

**Comment by Eggham** [comment]
@musnow Would you please point me to the full list of all encryption methods?

**Comment by musnow** [comment]
I am not quite sure about the specific support list, but the method described in the project is a list, you can refer to this url
https://github.com/shadowsocks/shadowsocks-libev#usage

Do you want to judge the list?
I think it’s better to follow the custom method. It seems that there is no special use in these places.

**Comment by Eggham** [comment]
thx. that's what I was looking for.

**Comment by Eggham** [comment]
done with da0f314
